### ISSUE TITLE
(Refactor) Listas de Valor

### ISSUE THREAD

**Issue by fmorales-mobdev** [MobDevCL/poc-autos-api#9]
Para evitar agregar listas de valor por cada sitio en el que se desee publicar, se considerarán listas de valor a partir de una estructura similar a esta:

```yaml
datasource:
  brands:
    "1":
      name: "Suzuki"
      externalIds:
        mercadolibre: "sdfgsfg"
      models:
        "1":
          name: "Swift"
          externalIds:
            mercadolibre: "sdfgsfg"
        "2":
          name: "Baleno"
          externalIds:
            mercadolibre: "sdfgsdfg"
    "2":
      name: "Toyota"
      models:
        "3":
          name: "Yaris"
          externalIds:
            mercadolibre: "sdfgs"
        "4":
          name: "Corolla"
          externalIds:
            mercadolibre: "sdfgsdfg"
```
